# Generated by Django 2.0.5 on 2018-06-01 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('active', models.IntegerField(choices=[(0, 0), (2, 2)], default=2)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('active', models.IntegerField(choices=[(0, 0), (2, 2)], default=2)),
                ('fb_id', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('active', models.IntegerField(choices=[(0, 0), (2, 2)], default=2)),
                ('original_link', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedditSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('active', models.IntegerField(choices=[(0, 0), (2, 2)], default=2)),
                ('name', models.CharField(max_length=100)),
                ('limit', models.IntegerField(default=10)),
                ('link', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='postlinks',
            name='subscribe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.RedditSubscription'),
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.PostLinks'),
        ),
    ]
