# Generated by Django 2.0.5 on 2018-06-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_postlinks_ups'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackOverflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('active', models.IntegerField(choices=[(0, 0), (2, 2)], default=2)),
                ('link', models.TextField()),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='site',
            field=models.IntegerField(choices=[(0, 'Reddit'), (1, 'StackOverflow')], default=0),
        ),
    ]
