# Generated by Django 2.0.5 on 2018-06-05 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20180605_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.StackOverflow'),
        ),
    ]
